Desktop/DjangoOnline/Student_Management/Student_Management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

Desktop/DjangoOnline/Student_Management/main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('',views.Index.as_view()),
    path('college/<int:pk>',views.CollegeDetail.as_view(),name='college'),
    path('college/', views.Collegelist.as_view()),
    path('createcollege/', views.CollegeCreate.as_view()),
    path('createstudent/', views.StudentCreate.as_view()),
    path('updatecollege/<int:pk>', views.CollegeUpdate.as_view()),
    path('deletestudent/<int:pk>', views.StudentDelete.as_view()),
]

Desktop/DjangoOnline/Student_Management/main/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name=models.CharField(max_length=256)
    roll_number=models.IntegerField(unique=True)
    college=models.ForeignKey('College',on_delete =models.CASCADE)

    def __str__(self):
        return self.name

class College(models.Model):
    name=models.CharField(max_length=256)

    def __str__(self):
        return self.name

Desktop/DjangoOnline/Student_Management/main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
# Create your views here.
from django.views.generic import(
    DetailView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)

from main import models

class Index(View):
    def get(self,request):
        return HttpResponse("GET request")

    def post(self,request):
        return HttpResponse("POST request")

class CollegeDetail(DetailView):
    model = models.College
    template_name ='college_detail.html'

class Collegelist(ListView):
    model=models.College
    template_name='collegelist.html'
    context_object_name='colleges'

class CollegeCreate(CreateView):
    model=models.College
    template_name='collegecreate.html'
    fields='__all__'
    success_url='/college'

class StudentCreate(CreateView):
    model=models.Student
    template_name='studentcreate.html'
    fields='__all__'
    success_url='/'


class CollegeUpdate(UpdateView):
    model = models.College
    template_name = 'collegecreate.html'
    fields='__all__'
    success_url='/college'



class StudentDelete(DeleteView):
    model = models.Student
    template_name = "confirm.html"
    success_url='/'

Desktop/DjangoOnline/Student_Management/templates/college_detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <h1>College</h1>
        Name: {{object.name}}
        <br>
        Students:
        <ul>
            {% for student in object.student_set.all %}
            <li>
                {{ student.name }}
            </li>
            {% endfor %}
        </ul>
</body>
</html>

Desktop/DjangoOnline/Student_Management/templates/collegecreate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>STUDENT MANAGEMENT</title>
</head>
<body>
   <h1>ADD COLLEGE</h1>
   <form action="" method="post">
    {% csrf_token %} 
    {{form}}
    <button type="submit">Submit</button>
   </form>
    
</body>
</html>

Desktop/DjangoOnline/Student_Management/templates/collegelist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Colleges</title>
</head>
<body>
    <ul>
        {% for college in colleges %}

        <li>
            <a href="{% url 'college' college.pk %}">{{college.name}}</a>
        </li>


        {% endfor %}
    </ul>
</body>
</html>

Desktop/DjangoOnline/Student_Management/templates/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        <label for="">Sure You Want To Delete</label>
        {% csrf_token %}
        {{form}}
        <button>No</button>
        <button type="submit">Yes</button>

    </form>
</body>
</html>

Desktop/DjangoOnline/Student_Management/templates/studentcreate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>ADD STUDENT</h1>
   <form action="" method="post">
    {% csrf_token %} 
    {{form}}
    <button type="submit">Submit</button>
   </form>
    
</body>
</html>